### ISSUE TITLE
Integration with existing Pokemon DB/APIs

### ISSUE THREAD

**Issue by jitinder** [scitbiz/flutter_pokedex#17]
While the point of having our own data stores and files makes sense, wouldn't it be better to use existing and more detailed resources and APIs like the PokeAPI? They contain all data for pokemon, items, locations etc. that can be used to complete the overall app...

**Comment by scitbiz** [comment]
@jitinder I tried using the PokeAPI before, but when I'm looking at the response of the API, I see it takes a lot of 
API request (like the evolution information) to get the data that this app needed, which will somehow slow the app down. Because the main purpose of the app is to show the performance/animation of Flutter and what Flutter can do, calling to many requests is not satisfy the case. Maybe I will implement it someday.

I've planned to create a server to be a bridge between PokeAPI and this app, fetching and converting to the right data structure so that this app can only need to make a few API requests, but I don't know when because it's a big task and I'm currently busy.

**Comment by jitinder** [comment]
Fair enough, I'll just close the issue if this is already something you've thought about :)

**Comment by scitbiz** [comment]
@jitinder Thanks for suggesting 😁
