### ISSUE TITLE
Pokemon image is not showed when the internet connection has been lost

### ISSUE THREAD

**Issue by jsmartinezn** [scitbiz/flutter_pokedex#35]
When i lost internet connection the pokemon images don't load

**Comment by scitbiz** [comment]
Hi @jsmartinezn,
Currently, this app doesn't save the image because there are too many of them (about ~1000 images). I'm considering 2 possible solutions:

1. Show the pokemon placeholder with a question mark (!) indicate that the image cannot be load due to the internet connection.
2. Add a new feature that will allow the user to download all the images and the pokemons into the device's storage so that the app can still be used in offline mode.

I think the latter will be better, what do you think?

**Comment by jsmartinezn** [comment]
Hi,

I prefered the first option because as the number of registered pokemon increases, it will not be feasible to store them all locally for memory space.
________________________________
De: Pham Sy Hung ***@***.***>
Enviado: martes, 1 de junio de 2021 10:57 p. m.
Para: scitbiz/flutter_pokedex ***@***.***>
Cc: Juan Sebastian Martinez Niño ***@***.***>; Mention ***@***.***>
Asunto: Re: [scitbiz/flutter_pokedex] Pokemon image bug (#35)


Hi @jsmartinezn<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjsmartinezn&data=04%7C01%7Cjs.martinezn%40uniandes.edu.co%7C979dd33833ae434a289908d9257a8cc7%7Cfabd047cff48492a8bbb8f98b9fb9cca%7C0%7C0%7C637582030543319176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xsm5ltBqEWrdDJYqRMJFGH%2Fr55iakm%2F7j4MbDTf3vzw%3D&reserved=0>,
Currently, this app doesn't save the image because there are too many of them (about ~1000 images). I'm considering 2 possible solutions:

  1.  Show the pokemon placeholder with a question mark (!) indicate that the image cannot be load due to the internet connection.
  2.  Add a new feature that will allow the user to download all the images and the pokemons into the device's storage so that the app can still be used in offline mode.

I think the latter will be better, what do you think?

**Comment by scitbiz** [comment]
@jsmartinezn Can you confirm https://github.com/scitbiz/flutter_pokedex/pull/39 solve your problem?
